analyzer:
  errors:
    use_build_context_synchronously: ignore
    invalid_annotation_target: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true # const 권장
    prefer_const_literals_to_create_immutables: true # 불변 리스트에 const 자동 추가
    prefer_final_locals: true # 불변 변수에 final 권장
