name: travel_tts
description: "여행자를 위한 오프라인/온라인 TTS 앱"

version: 1.0.1+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  connectivity_plus: ^6.1.5
  internet_connection_checker_plus: ^2.7.2
  speech_to_text: ^7.3.0
  go_router: ^16.0.0
  permission_handler: ^12.0.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  flutter_dotenv: ^6.0.0
  device_info_plus: ^11.3.3
  intl: ^0.20.2
  path: ^1.9.0
  dio: ^5.8.0+1
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  bot_toast: ^4.1.3
  sizer: ^3.0.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  shared_preferences: ^2.5.3
  google_mlkit_translation: ^0.13.0
  skeletonizer: ^2.1.0+1
  google_mobile_ads: ^6.0.0
  google_mlkit_language_id: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/traveltalk_icon.png