// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2uJAkzb4-kTcrzPBXtSYDOb27PoShnS0',
    appId: '1:877151868324:web:f32a025379c31de73b5d31',
    messagingSenderId: '877151868324',
    projectId: 'travel-tts',
    authDomain: 'travel-tts.firebaseapp.com',
    storageBucket: 'travel-tts.firebasestorage.app',
    measurementId: 'G-9N0VMK4VEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgADNCiIlf86UiBFCxqPVCu1dW7mEDh8',
    appId: '1:877151868324:android:fa31833e089f56f03b5d31',
    messagingSenderId: '877151868324',
    projectId: 'travel-tts',
    storageBucket: 'travel-tts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLF9CSo1pcJ-XviKmAG3iFOZoegUkRoI',
    appId: '1:877151868324:ios:432ca98c3de783b03b5d31',
    messagingSenderId: '877151868324',
    projectId: 'travel-tts',
    storageBucket: 'travel-tts.firebasestorage.app',
    iosBundleId: 'com.example.travelTts',
  );

}